### ISSUE TITLE
Crash on startup with GT6 enabled: Deepslate

### ISSUE THREAD

**Issue by tyrael93** [jss2a98aj/Et-Futurum#19]
Deepslate is currently disabled. I'm assuming GT6 is trying to create deepslate ore.
>Caused by: java.lang.ClassCastException: net.minecraft.block.BlockOre incompatible with ganymedes01.etfuturum.IConfigurable
	at ganymedes01.etfuturum.blocks.ores.BlockDeepslateOre.setAttribs(BlockDeepslateOre.java:55)
	at ganymedes01.etfuturum.blocks.ores.BlockDeepslateOre.<init>(BlockDeepslateOre.java:42)
	at ganymedes01.etfuturum.ModBlocks.<clinit>(ModBlocks.java:181)
	... 47 more

Here's the crashlog: https://pastebin.com/wCdmpxFT

Thanks in advance.

**Comment by Roadhog360** [comment]
New release 2.1.1 should fix this.
